### ISSUE TITLE
[feature] Filter and sort settings for set list

### ISSUE THREAD

**Issue by JeffCorract** [leolelego/Brickie-iOS#60]

**Comment by leolelego** [comment]
@JeffCorract I think of this too, actually I will rework the database to be a CoreData, so this kind of feature will be easier to do! 

Do have some sort and filter you want first ?

**Comment by leolelego** [comment]
@JeffCorract First draft, you ask the good day, I wanted to wrk on it! 
What do you thing of these sorter ? 

What filter do you want ? I have already "wanted", I think of rating, other ideas ?

![filter](https://user-images.githubusercontent.com/4069471/98483616-42c29d80-220a-11eb-96e3-91801402e5c9.gif)

**Comment by JeffCorract** [comment]
Hi,
Wow that was fast ;)
Sort by year looks very good.
Does Brickset API also provide the possibility to sort by date added?
That would be nice too. 
Filters are not my prio one as well. But if it's on your roadmap I would suggest:
Filter by category and year.

**Comment by leolelego** [comment]
@JeffCorract Hi, so sort by year and alphabetical is mostly done. I have done filter by favourite/want and owned in list view from a selected year on set. I can try to filter by year. Let me thing of it, I fill this require more work, but, lets see. 

I which I can filter by date added, because I want that too, but the API does not. I saw this information on Brickset somewhere, so I think this exist. But not sure!

**Comment by leolelego** [comment]
@JeffCorract you can try the beta with the feature requested here : https://testflight.apple.com/join/9IE197Mt

**Comment by leolelego** [comment]
this is available on version 1.2 coming soon!
