### ISSUE TITLE
SwiftUI Previews not working

### ISSUE THREAD

**Issue by BrianBatchelder** [leolelego/Brickie-iOS#99]
Hello,

SwiftUI Previews were not working "out of the box". I made some changes to make them work. Which leads to a couple of questions:
- Are SwiftUI Previews working for you?
- Would you like me to submit my fixes as a PR?

Thanks, Brian

**Comment by leolelego** [comment]
Hi @BrianBatchelder 

I will be honest, I don't use Preview, that's why I removed them. I'm kind of old school on this. And everytime I tried to use them I felt that is slower than build on Simulator. 

If you can make them work with fallback data/objects it will be appreciated, I saw you already start on your branch. Just make sure the PR don't break anything like add fallback data on real object that can be `nil` etc.

**Comment by BrianBatchelder** [comment]
Hey, @leolelego

I find Preview useful, especially when working on views well down in the view stack. Also, I found a way to run the previews in the simulator fairly easily, now that Xcode no longer allows debugging of Previews directly (which is unfortunate). I've just been playing with it mostly, but I'll see if I can make it PR-ready.

**Comment by leolelego** [comment]
Hey @BrianBatchelder 
I can confess that this could be welcome! 

I merge your 2 PRs and it's included in 1.5 branch (hopefully for Feb) 😊 You will be mentionned in the App Release note on AppStore if it's ok for you. 

https://github.com/leolelego/Brickie-iOS/commit/63150e371e9e300c46f4890f4a02c36ddc747c40

**Comment by leolelego** [comment]
Hey @BrianBatchelder 
I merge your code here but I got issues on UI. the Tabbar is not here and some "theme" colors are not working. 
I will try to fix them but do theses issues was already here or it's from the merge ?

https://github.com/leolelego/Brickie-iOS/tree/merge1.5-brianpreview-fix

**Comment by leolelego** [comment]
Integrated in branch 1.5
